<!DOCTYPE html>
<html lang="en">
  
    <meta charset="utf-8" />
    <style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

    <title></title>
  
  <body>
<?php 




?>
<div id="welcome">
    <h1> <span id="zf-name"></span></h1>

    <h3></h3>

    <div id="more-information">
        <p><img src="" /></p>
        <p>
            Новости: <br />
            <a href=""></a> |
            <a href=""></a>
        </p>
    </div>
</div>
      </body>
</html>