<!DOCTYPE html>
<html lang="en">
  
    <meta charset="utf-8" />
    <style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

<body>
  
 

<div id="welcome">
    <h1>ВАША СКОРОСТЬ
        <?php 
    echo '<pre>';
        print_r($this->json_data->entries[0]->speed);
?> КМ.Ч.
    </h1>

    <h3></h3>

    <div id="more-information">
       
                <p>
             <br />
            <a href="#"></a> |
            <a href="#"></a>
        </p>
    </div>
</div>
    
    <?php 
    echo '<pre>';
        print_r($this->json_data->entries[0]->speed);
?>
</body>
</html>