<!DOCTYPE html>
<html lang="en">
  
    <meta charset="utf-8" />
    <style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

    <title></title>
  
  <body></body>

<div id="welcome">
    <h1>News<span id="zf-name">Новости</span></h1>

    <h3>Свежие новости</h3>

    <div id="more-information">
                <p>
            Публикуем ссылки на ZF2: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>
</html>