<!DOCTYPE html>
<html lang="en">
    <!-- vim: ts=2:sw=2:nu:fdc=2:spell
     
    An Application Page NEWS zf1-stud.local
     
    @author    Ivan Eremin
    @copyright (c) 2014, by Ing. Ivan Eremin
    @date      12. Aug 2014
    @version   $Id: 
     
    @license application.html is licensed under the terms of the Open Source
    LGPL 3.0 license. Commercial use is permitted to the extent that the 
    code/component(s) do NOT become part of another Open Source or Commercially
    licensed development library or toolkit without explicit permission.
     
    License details: http://www.gnu.org/licenses/lgpl.html
    -->
    
    
    <head>
    <style>
        .delete-icon {
    width: 2em;
    height: 2em;
    background: red;
}</style>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="/js/ext/resources/css/ext-all.css">
        <script type="text/javascript" src="/js/ext/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="/js/ext/ext-all-debug.js"></script>
        <script type="text/javascript" src="/js/news.js"></script>
    </head>
    <!-- Layout Mandatory Styles -->
<head>
<body>
</body>
</html>
<!-- eof -->