<!DOCTYPE html>
<html lang="en">
  
    <meta charset="utf-8" />

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application - страница ошибки</title>
</head>
<body>
  <h1>An error occurred</h1>
  <h1>Ошибка, что-то пошло не так</h1>
    
  <img src="http://abunda.ru/uploads/posts/2012-06/1340754988_024_26733_24.jpg" alt="Письма мастера дзен"></img>
  
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>

</body>
</html>
